#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script was generated by Tim Kluser with the assistance of GitHub Copilot

import os
# patch because it can't find the pyproj maps
os.environ["PROJ_LIB"] = "/users/tkluser/miniforge3/envs/qpe_plots/share/proj"
import pyproj
pyproj.datadir.set_data_dir("/users/tkluser/miniforge3/envs/qpe_plots/share/proj")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from pyproj import Transformer

INPUT_DIR_GAUGEDATA = "/store_new/mch/msrad/radar/radar_database_v2/rf_input_data_qc/"
STATIONS_CSV = "/store_new/mch/msrad/radar/rainforest_data/references/metadata/data_stations.csv"
OUT_DIR = "analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "RF": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_noPostProcess/cv_pred_RF_noPostProcess_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
    "GRU_bidirectional": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_Bidirectional/cv_1_GRU_Bidirectional_all_folds.parquet",
}

EST_COL = "y_pred"
REF_COL = "y_obs"


def load_and_compute_logbias():
    print("Loading station metadata and gauge data...")
    df_stations = pd.read_csv(STATIONS_CSV, encoding='latin1', sep=";")
    gauge = pd.read_parquet(os.path.join(INPUT_DIR_GAUGEDATA, "gauge.parquet"), columns=["STATION"])
    
    transformer = Transformer.from_crs("EPSG:21781", "EPSG:4326", always_xy=True)
    
    def convert_coords(row):
        lon, lat = transformer.transform(row['Y'], row['X'])
        return pd.Series([lat, lon])
        
    df_stations[['lat', 'lon']] = df_stations.apply(convert_coords, axis=1)
    
    model_results = {}

    for method, path in MODELS.items():
        if not os.path.exists(path):
            print(f"Skipping {method}: File not found ({path})")
            continue
            
        print(f"Processing data for {method}...")
        df = pd.read_parquet(path)
        
        if "split" in df.columns:
            df = df[df["split"].astype(str).str.lower() == "test"]
        elif "is_train" in df.columns:
            df = df[~df["is_train"].astype(bool)]
            
        df = pd.merge(df, gauge, left_on="vertgroup", right_index=True)
        
        # Apply double threshold > 0.1 as defined in utils.py
        valid_mask = (df[EST_COL] > 0) & (df[REF_COL] > 0)
        df_valid = df[valid_mask]
        # df_valid = df

        df_sums = df_valid.groupby("STATION").agg(
            est_sum=(EST_COL, "sum"),
            ref_sum=(REF_COL, "sum")
        ).reset_index()
        
        # Avoid divisions by zero
        # safe_mask = (df_sums["est_sum"] > 0) & (df_sums["ref_sum"] > 0)
        # df_sums = df_sums[safe_mask].copy()
        df_sums = df_sums.copy()
        
        df_sums["logBias"] = 10 * np.log10(df_sums["est_sum"] / df_sums["ref_sum"])
        
        # Merge coordinates onto the results
        df_final = pd.merge(df_sums, df_stations, left_on="STATION", right_on="Abbrev")
        model_results[method] = df_final

    return model_results

def plot_swiss_map_grid(model_results):
    print("Generating map grid plot...")
    
    vmin, vmax = -2.5, 2.5 
    
    methods = list(MODELS.keys())
    
    fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(10, 7), 
                             subplot_kw={'projection': ccrs.PlateCarree()})
    
    fig.subplots_adjust(wspace=0, hspace=0, bottom=0.15)
    
    extent_ch = [5.8, 10.6, 45.7, 47.9]
    sc = None 
    
    for i, method in enumerate(methods):
        ax = axes[i // 2, i % 2]
        
        ax.set_extent(extent_ch, crs=ccrs.PlateCarree())
        
        # Add bacxkground styling
        ax.add_feature(cfeature.LAND, facecolor='#dddddd') # Light gray background
        ax.add_feature(cfeature.BORDERS, linewidth=1.5, edgecolor='black')
        
        # Ensure the bounding box around the map is visible
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(1.0)
        
        if method not in model_results:
            ax.text(0.5, 0.5, "Data Unavailable", transform=ax.transAxes, ha='center', va='center')
            continue
            
        df = model_results[method]
        
        sc = ax.scatter(df['lon'], df['lat'], 
                        c=df['logBias'], 
                        cmap='RdBu_r',  # Red-Blue diverging, reversed (Blue=negative, Red=positive)
                        s=45,           
                        alpha=0.9, 
                        edgecolors='none', 
                        transform=ccrs.PlateCarree(),
                        vmin=vmin, 
                        vmax=vmax)
        
        ax.text(0.03, 0.95, method, transform=ax.transAxes, fontsize=10, 
                fontweight='bold', va='top', ha='left',
                bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=2))

    if sc is not None:
        # [left, bottom, width, height]
        cbar_ax = fig.add_axes([0.2, 0.05, 0.6, 0.04]) 
        cbar = fig.colorbar(sc, cax=cbar_ax, orientation='horizontal', extend='both')
        cbar.set_label('logBias', fontsize=12)
        cbar.ax.tick_params(labelsize=10)

    plt.tight_layout()

    out_path = os.path.join(OUT_DIR, "station_logbias_map_grid.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"\nSuccess! Plot saved to: {out_path}")

if __name__ == "__main__":
    results_dict = load_and_compute_logbias()
    if results_dict:
        plot_swiss_map_grid(results_dict)
    else:
        print("No data was successfully loaded. Plot not generated.")