#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script was generated by Tim Kluser with the assistance of GitHub Copilot
# script that calculates performance metrics per vertgroup size/length


import os
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from utils import perfscores

INPUT_DIR_GAUGEDATA = "/store_new/mch/msrad/radar/radar_database_v2/rf_input_data_qc/"
OUT_DIR = "./analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
}

EST_COL = "y_pred"
REF_COL = "y_obs"
LOW_PRECIP_BOUND = 2 / 6
LOW_LABEL = r"$R < 2\ \mathrm{mm/h}$"

METRICS = ["scatter", "RMSE", "logBias", "ED"]
COLORS = {'RF_spline': '#1f77b4', 'GRU_optimized': '#ff7f0e'}
BIN_WIDTH = 2


def load_vertgroup_sizes():
    """
    Load radar data and compute the number of measurements per vertgroup.
    """
    print("Loading radar data and grouping indices...")
    grouping_path = os.path.join(INPUT_DIR_GAUGEDATA, "grouping_idx_x0y0.p")
    with open(grouping_path, "rb") as f:
        grouping = pickle.load(f)

    vertgroups = np.asarray(grouping["grp_vertical"])
    group_sizes = pd.Series(vertgroups).value_counts().sort_index()
    group_sizes.index.name = "vertgroup"
    group_sizes.name = "n_measurements"

    print(f"Loaded {len(group_sizes)} unique vertgroups")
    return group_sizes


def load_and_merge_data(group_sizes):
    all_data = []
    for method, path in MODELS.items():
        if not os.path.exists(path):
            print(f"Skipping {method}: File not found ({path})")
            continue

        print(f"Loading predictions for {method}")
        df = pd.read_parquet(path)

        if "split" in df.columns:
            df["__split__"] = df["split"].astype(str).str.lower()
        elif "is_train" in df.columns:
            df["__split__"] = np.where(df["is_train"].astype(bool), "train", "test")

        df["__fold__"] = df["fold"].astype(str) if "fold" in df.columns else "1"
        df["method"] = method

        if "vertgroup" in df.columns:
            df = pd.merge(df, group_sizes.reset_index(), on="vertgroup", how="inner")
        else:
            raise KeyError(f"Column 'vertgroup' missing in {method} data.")

        all_data.append(df)

    return pd.concat(all_data, ignore_index=True)


def bin_and_compute_metrics(df):
    df_test = df[df["__split__"] == "test"].copy()
    max_size = 36
    bins = np.arange(0, max_size + BIN_WIDTH, BIN_WIDTH)
    labels = bins[:-1] + (BIN_WIDTH / 2)
    df_test["size_bin"] = pd.cut(df_test["n_measurements"], bins=bins, labels=labels, include_lowest=True)

    print("Computing metrics across bins and folds")

    bin_stats = {}
    base_method = list(MODELS.keys())[0]

    for size_bin, d_bin in df_test[df_test["method"] == base_method].groupby("size_bin", observed=False):
        n_total = len(d_bin)
        n_low = len(d_bin[d_bin[REF_COL] < LOW_PRECIP_BOUND])
        ratio_low = float(n_low / n_total) if n_total > 0 else np.nan

        bin_stats[size_bin] = {
            "N": n_total,
            "N_low": n_low,
            "ratio_low": ratio_low,
            "med_ref": d_bin[REF_COL].median() if n_total > 0 else 0,
            "mean_ref": d_bin[REF_COL].mean() if n_total > 0 else 0,
        }

    rows = []
    for (method, fold, size_bin), d_group in df_test.groupby(["method", "__fold__", "size_bin"], observed=False):
        if len(d_group) == 0:
            continue

        metrics_all = perfscores(d_group[EST_COL].to_numpy(), d_group[REF_COL].to_numpy())
        metrics_low = perfscores(
            d_group[EST_COL].to_numpy(),
            d_group[REF_COL].to_numpy(),
            bounds=[0, LOW_PRECIP_BOUND, np.inf]
        ).get("{:2.1f}-{:2.1f}".format(0.0, LOW_PRECIP_BOUND), {})

        for metric_name in METRICS:
            all_val = metrics_all.get("all", {}).get(metric_name, np.nan)
            low_val = metrics_low.get(metric_name, np.nan)

            rows.append({
                "method": method,
                "fold": fold,
                "size_bin": size_bin,
                "subset": "all",
                "metric": metric_name,
                "value": float(all_val) if np.isfinite(all_val) else np.nan,
            })
            rows.append({
                "method": method,
                "fold": fold,
                "size_bin": size_bin,
                "subset": "low",
                "metric": metric_name,
                "value": float(low_val) if np.isfinite(low_val) else np.nan,
            })

    return pd.DataFrame(rows), bin_stats


def plot_grid(metrics_df, bin_stats):
    print("Generating plot with low-precip dashed lines and ratio bars...")

    fig, axes = plt.subplots(2, 2, figsize=(15, 10), sharex=True)
    axes = axes.flatten()

    methods = list(MODELS.keys())
    line_handles, line_labels = [], []
    bar_handle = None
    low_bar_handle = None

    valid_bins = sorted([b for b, stats in bin_stats.items() if stats["N"] > 0])
    x_vals_bg = np.array(valid_bins, dtype=float)
    med_vals = np.array([bin_stats[b]["med_ref"] for b in valid_bins])
    mean_vals = np.array([bin_stats[b]["mean_ref"] for b in valid_bins])
    n_vals = np.array([bin_stats[b]["N"] for b in valid_bins])
    n_low_vals = np.array([bin_stats[b]["N_low"] for b in valid_bins])
    ratio_vals = np.array([bin_stats[b]["ratio_low"] for b in valid_bins])

    for i, metric in enumerate(METRICS):
        ax = axes[i]
        d_metric = metrics_df[metrics_df["metric"] == metric]

        enum_letter = chr(ord('a') + i)
        ax.set_title(f"{enum_letter}) {metric}", loc='left', fontsize=14, fontweight='bold', pad=10)

        ax.set_zorder(10)
        ax.patch.set_visible(False)

        ax2 = ax.twinx()

        ax2.set_zorder(1)

        total_bars = ax2.bar(x_vals_bg, n_vals, width=BIN_WIDTH * 0.8, color='lightgray', alpha=0.3, zorder=4)
        low_bars = ax2.bar(x_vals_bg, n_low_vals, width=BIN_WIDTH * 0.8, color="#BABABA", alpha=0.3, zorder=4)
        if i == 0:
            bar_handle = total_bars[0]
            low_bar_handle = low_bars[0]

        y_offset = max(n_vals) * 0.03 if len(n_vals) > 0 else 0
        for x, ratio, n in zip(x_vals_bg, ratio_vals, n_vals):
            if np.isfinite(ratio):
                ax2.text(x, n + y_offset, f"{ratio:.0%}", ha='center', va='bottom', fontsize=9, color='dimgray', rotation=90)

        for k, method in enumerate(methods):
            d_method_all = d_metric[(d_metric["method"] == method) & (d_metric["subset"] == "all")]
            d_method_low = d_metric[(d_metric["method"] == method) & (d_metric["subset"] == "low")]

            grp_all = d_method_all.groupby("size_bin", observed=False)["value"]
            means_all = grp_all.mean()
            stds_all = grp_all.std().fillna(0)

            grp_low = d_method_low.groupby("size_bin", observed=False)["value"]
            means_low = grp_low.mean()
            stds_low = grp_low.std().fillna(0)

            valid_idx_all = means_all.notna()
            x_vals_all = means_all.index.astype(float)[valid_idx_all]
            y_means_all = means_all.values[valid_idx_all]
            y_stds_all = stds_all.values[valid_idx_all]

            valid_idx_low = means_low.notna()
            x_vals_low = means_low.index.astype(float)[valid_idx_low]
            y_means_low = means_low.values[valid_idx_low]
            y_stds_low = stds_low.values[valid_idx_low]

            line, = ax.plot(
                x_vals_all,
                y_means_all,
                marker='o',
                color=COLORS[method],
                label=method,
                linewidth=2.5,
                markersize=5,
                alpha=0.9,
                zorder=3
            )
            ax.fill_between(x_vals_all, y_means_all - y_stds_all, y_means_all + y_stds_all, color=COLORS[method], alpha=0.2, zorder=2)

            dashed, = ax.plot(
                x_vals_low,
                y_means_low,
                marker='x',
                linestyle='--',
                color=COLORS[method],
                label=f"{method} {LOW_LABEL}",
                linewidth=2.0,
                markersize=5,
                alpha=0.9,
                zorder=3
            )
            ax.fill_between(x_vals_low, y_means_low - y_stds_low, y_means_low + y_stds_low, color=COLORS[method], alpha=0.1, zorder=2)

            if i == 0:
                line_handles.append(line)
                line_labels.append(method)
                line_handles.append(dashed)
                line_labels.append(f"{method} {LOW_LABEL}")

        ax2.set_ylim(0, ax2.get_ylim()[1] * 1.35)

        ax.set_ylabel(f"{metric}", fontsize=12)
        ax2.set_ylabel("Number of Samples (N)", fontsize=11, color='gray')
        ax2.tick_params(axis='y', labelcolor='gray')

        ax.grid(axis='y', linestyle='--', alpha=0.5)
        ax.grid(axis='x', linestyle='--', alpha=0.5)

        if i >= 2:
            ax.set_xlabel("Vertgroup Size (Nr. Radar Measurements)", fontsize=13)

    all_handles = line_handles + [bar_handle, low_bar_handle]
    all_labels = line_labels + ["Number of Samples", f"Samples with {LOW_LABEL}"]
    fig.legend(all_handles, all_labels, loc='upper center', bbox_to_anchor=(0.5, 1.05), ncol=4, frameon=True, fontsize=11)

    plt.tight_layout()
    out_path = os.path.join(OUT_DIR, "vertgroup_size_metrics_low_precip_with_uncertainty.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Plot successfully saved to: {out_path}")


if __name__ == "__main__":
    group_sizes = load_vertgroup_sizes()
    df_raw = load_and_merge_data(group_sizes)
    df_metrics, bin_stats = bin_and_compute_metrics(df_raw)
    plot_grid(df_metrics, bin_stats)
