#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script was generated by Tim Kluser with the assistance of GitHub Copilot
# script that calculates mean precipitation and mean height of radar observations per vertgroup size/length


import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pyarrow import parquet as pq

INPUT_DIR_GAUGEDATA = "/store_new/mch/msrad/radar/radar_database_v2/rf_input_data_qc/"
OUT_DIR = "./analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

PRECIP_COL = "RRE150Z0"
HEIGHT_COL = "HEIGHT"
LOW_PRECIP_BOUND = 2.0 / 6.0


def load_grouping():
    grouping_path = os.path.join(INPUT_DIR_GAUGEDATA, "grouping_idx_x0y0.p")
    if not os.path.exists(grouping_path):
        raise FileNotFoundError(f"Missing grouping file: {grouping_path}")

    print("Loading grouping indices...")
    import pickle

    with open(grouping_path, "rb") as f:
        grouping = pickle.load(f)

    if "grp_vertical" not in grouping:
        raise KeyError("grouping_idx_x0y0.p does not contain 'grp_vertical'")

    grp_vertical = np.asarray(grouping["grp_vertical"], dtype=np.int64)
    if grp_vertical.size == 0:
        raise ValueError("grp_vertical is empty")

    n_groups = grp_vertical.max() + 1
    print(f"Found {n_groups:,} vertgroups and {grp_vertical.size:,} radar measurements")
    return grp_vertical, n_groups


def load_gauge_precip(n_groups):
    gauge_path = os.path.join(INPUT_DIR_GAUGEDATA, "gauge.parquet")
    if not os.path.exists(gauge_path):
        raise FileNotFoundError(f"Missing gauge file: {gauge_path}")

    print("Loading gauge precipitation reference values...")
    df = pd.read_parquet(gauge_path, columns=[PRECIP_COL])
    precip = df[PRECIP_COL].astype(float).to_numpy(copy=False)

    if precip.shape[0] < n_groups:
        raise ValueError(
            f"Gauge file contains {precip.shape[0]:,} rows but grouping expects {n_groups:,} vertgroups"
        )
    elif precip.shape[0] > n_groups:
        precip = precip[:n_groups]

    return precip


def compute_vertgroup_height_means(grp_vertical, n_groups):
    radar_path = os.path.join(INPUT_DIR_GAUGEDATA, "radar_x0y0.parquet")
    if not os.path.exists(radar_path):
        raise FileNotFoundError(f"Missing radar file: {radar_path}")

    print("Aggregating radar measurement heights per vertgroup...")
    parquet_file = pq.ParquetFile(radar_path)
    height_sums = np.zeros(n_groups, dtype=np.float64)
    height_counts = np.zeros(n_groups, dtype=np.int64)

    offset = 0
    for rg in range(parquet_file.num_row_groups):
        table = parquet_file.read_row_group(rg, columns=[HEIGHT_COL])
        heights = table.column(HEIGHT_COL).to_pandas().to_numpy(dtype=float)
        idx = grp_vertical[offset : offset + heights.shape[0]]
        offset += heights.shape[0]

        valid = np.isfinite(heights)
        if not np.any(valid):
            continue

        np.add.at(height_sums, idx[valid], heights[valid])
        np.add.at(height_counts, idx[valid], 1)

        if (rg + 1) % 10 == 0 or rg == parquet_file.num_row_groups - 1:
            print(f"  processed row group {rg + 1}/{parquet_file.num_row_groups}")

    if offset != grp_vertical.size:
        raise ValueError(
            f"Row count mismatch: grouping array has {grp_vertical.size:,} rows but parquet file read {offset:,} rows"
        )

    height_means = np.full(n_groups, np.nan, dtype=np.float64)
    valid_groups = height_counts > 0
    height_means[valid_groups] = height_sums[valid_groups] / height_counts[valid_groups]

    n_valid = np.sum(valid_groups)
    print(f"Computed height mean for {n_valid:,} vertgroups")
    return height_means


def aggregate_by_size(group_sizes, precip, height_means):
    print("Aggregating mean precip and height by vertgroup size...")
    df = pd.DataFrame(
        {
            "size": group_sizes,
            "precip": precip,
            "height": height_means,
        }
    )

    valid = df["size"] > 0
    df = df.loc[valid].copy()

    grouped = df.groupby("size", observed=False)
    agg = grouped[["precip", "height"]].mean()
    agg = agg.rename(columns={"precip": "mean_precip_all", "height": "mean_height"})

    low_mask = df["precip"] < LOW_PRECIP_BOUND
    if low_mask.any():
        agg_low_precip = df.loc[low_mask].groupby("size", observed=False)["precip"].mean()
        agg_low_height = df.loc[low_mask].groupby("size", observed=False)["height"].mean()
        agg["mean_precip_low"] = agg_low_precip
        agg["mean_height_low"] = agg_low_height
    else:
        agg["mean_precip_low"] = np.nan
        agg["mean_height_low"] = np.nan

    agg["count"] = grouped.size()
    agg = agg.sort_index()
    return agg


def plot_aggregates(agg):
    print("Plotting aggregate means for vertgroup sizes...")
    sizes = agg.index.astype(float)
    all_precip = agg["mean_precip_all"].to_numpy()
    low_precip = agg["mean_precip_low"].to_numpy()
    mean_height = agg["mean_height"].to_numpy()
    mean_height_low = agg["mean_height_low"].to_numpy()

    fig, ax_precip = plt.subplots(figsize=(14, 7))
    ax_height = ax_precip.twinx()

    ax_precip.plot(sizes, all_precip, marker="o", color="#1f77b4", label="Mean precip (all)")
    ax_precip.plot(sizes, low_precip, marker="s", linestyle="--", color="#ff7f0e", label=f"Mean precip (< 2 mm/h)")
    ax_height.plot(sizes, mean_height, marker="^", linestyle="-.", color="#2ca02c", label="Mean height (all)")
    ax_height.plot(sizes, mean_height_low, marker="v", linestyle=":", color="#9467bd", label=f"Mean height (< 2 mm/h)")

    ax_precip.set_xlabel("Vertgroup size (number of radar measurements)")
    ax_precip.set_ylabel("Mean gauge precipitation [mm/10min]", color="#1f77b4")
    ax_height.set_ylabel("Mean radar measurement height [m]", color="#2ca02c")
    ax_precip.set_title(
        "Mean gauge precipitation and mean radar height by vertgroup size"
    )
    ax_precip.grid(axis="x", linestyle="--", alpha=0.3)

    lines_precip, labels_precip = ax_precip.get_legend_handles_labels()
    lines_height, labels_height = ax_height.get_legend_handles_labels()
    ax_precip.legend(lines_precip + lines_height, labels_precip + labels_height, loc="upper left", fontsize=10)

    plt.tight_layout()
    out_path = os.path.join(OUT_DIR, "vertgroup_size_mean_precip_height.png")
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved plot to: {out_path}")


def main():
    grp_vertical, n_groups = load_grouping()
    group_sizes = np.bincount(grp_vertical)
    precip = load_gauge_precip(n_groups)
    height_means = compute_vertgroup_height_means(grp_vertical, n_groups)
    agg = aggregate_by_size(group_sizes, precip, height_means)
    plot_aggregates(agg)


if __name__ == "__main__":
    main()
