#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script was generated by Tim Kluser with the assistance of GitHub Copilot

import os
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the perfscores function from your utils.py
from utils import perfscores


INPUT_DIR_GAUGEDATA = "/store_new/mch/msrad/radar/radar_database_v2/rf_input_data_qc/"
OUT_DIR = "./analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
}

EST_COL = "y_pred"
REF_COL = "y_obs"

METRICS = ["scatter", "RMSE", "logBias", "ED"]
COLORS = {'RF_spline': '#1f77b4', 'GRU_optimized': '#ff7f0e'}
BIN_WIDTH = 2


def load_vertgroup_sizes():
    """
    Load radar data and compute the number of measurements per vertgroup.
    """
    print("Loading radar data and grouping indices...")
    # radar = pd.read_parquet(
    #     os.path.join(INPUT_DIR_GAUGEDATA, "radar_x0y0.parquet"),
    #     columns=["RADAR"] 
    # )
    
    grouping_path = os.path.join(INPUT_DIR_GAUGEDATA, "grouping_idx_x0y0.p")
    with open(grouping_path, "rb") as f:
        grouping = pickle.load(f)
    
    vertgroups = np.asarray(grouping["grp_vertical"])
    
    # Count measurements per vertgroup
    # the n'th entry of the grp_vertical with value x maps the n'th entry of
    # the radar dataframe to the x'th column of the gauge dataframe 
    # -> therefore the values of grp_vertical are the indices of the gauge frame
    group_sizes = pd.Series(vertgroups).value_counts().sort_index()
    group_sizes.index.name = "vertgroup"
    group_sizes.name = "n_measurements"
    
    print(f"Loaded {len(group_sizes)} unique vertgroups")
    return group_sizes


def load_and_merge_data(group_sizes):
    all_data = []
    for method, path in MODELS.items():
        if not os.path.exists(path):
            print(f"Skipping {method}: File not found ({path})")
            continue
            
        print(f"Loading predictions for {method}")
        df = pd.read_parquet(path)
        
        if "split" in df.columns:
            df["__split__"] = df["split"].astype(str).str.lower()
        elif "is_train" in df.columns:
            df["__split__"] = np.where(df["is_train"].astype(bool), "train", "test")
            
        # Extract the fold to compute standard deviations later
        df["__fold__"] = df["fold"].astype(str) if "fold" in df.columns else "1"
        df["method"] = method
        
        if "vertgroup" in df.columns:
            df = pd.merge(df, group_sizes.reset_index(), on="vertgroup", how="inner")
        else:
            raise KeyError(f"Column 'vertgroup' missing in {method} data.")
            
        all_data.append(df)
        
    return pd.concat(all_data, ignore_index=True)

def bin_and_compute_metrics(df):
    df_test = df[df["__split__"] == "test"].copy()
    
    # max_size = int(np.ceil(df_test["n_measurements"].max() / BIN_WIDTH)) * BIN_WIDTH
    max_size = 36 # hardcode because the last bins only get a few predictions
    bins = np.arange(0, max_size + BIN_WIDTH, BIN_WIDTH)
    labels = bins[:-1] + (BIN_WIDTH / 2)
    
    df_test["size_bin"] = pd.cut(df_test["n_measurements"], bins=bins, labels=labels, include_lowest=True)
    
    print("Computing metrics across bins and folds")
    
    # Compute global N and median ref per bin (Using only one model's test set to avoid double-counting)
    bin_stats = {}
    base_method = list(MODELS.keys())[0]
    
    for size_bin, d_bin in df_test[df_test["method"] == base_method].groupby("size_bin", observed=False):
        bin_stats[size_bin] = {
            "N": len(d_bin),
            "med_ref": d_bin[REF_COL].median() if len(d_bin) > 0 else 0,
            "mean_ref": d_bin[REF_COL].mean() if len(d_bin) > 0 else 0
        }
        
    # Compute the metric values independently per fold
    rows = []
    for (method, fold, size_bin), d_group in df_test.groupby(["method", "__fold__", "size_bin"], observed=False):
        if len(d_group) == 0:
            continue
            
        metrics_all = perfscores(d_group[EST_COL].to_numpy(), d_group[REF_COL].to_numpy())
        mdict = metrics_all.get("all", {})
        
        for metric_name in METRICS:
            val = mdict.get(metric_name, np.nan)
            rows.append({
                "method": method,
                "fold": fold,
                "size_bin": size_bin,
                "metric": metric_name,
                "value": float(val) if np.isfinite(val) else np.nan,
            })
            
    return pd.DataFrame(rows), bin_stats


def plot_grid(metrics_df, bin_stats):
    print("Generating plot with uncertainty regions...")
    
    fig, axes = plt.subplots(2, 2, figsize=(15, 10), sharex=True)
    axes = axes.flatten()
    
    methods = list(MODELS.keys())
    line_handles, line_labels = [], []
    bar_handle = None
    
    # Extract data for the background bars
    valid_bins = sorted([b for b, stats in bin_stats.items() if stats["N"] > 0])
    x_vals_bg = np.array(valid_bins)
    med_vals = np.array([bin_stats[b]["med_ref"] for b in valid_bins])
    mean_vals = np.array([bin_stats[b]["mean_ref"] for b in valid_bins])
    n_vals = np.array([bin_stats[b]["N"] for b in valid_bins])
    
    for i, metric in enumerate(METRICS):
        ax = axes[i]
        d_metric = metrics_df[metrics_df["metric"] == metric]
        
        # Subplot Enumeration
        enum_letter = chr(ord('a') + i)
        ax.set_title(f"{enum_letter}) {metric}", loc='left', fontsize=14, fontweight='bold', pad=10)
        
        # Secondary axis for the background bars (Number of Samples)
        ax2 = ax.twinx()
        
        # Plot Background Bars (Number of Samples)
        bars = ax2.bar(x_vals_bg, n_vals, width=BIN_WIDTH * 0.8, color='gray', alpha=0.25, label="Number of Samples")
        if i == 0:
            bar_handle = bars[0]
            
        # Add Median/mean Precip annotations above bars
        y_offset = max(n_vals) * 0.03 if len(n_vals) > 0 else 0
        for x, m_val, n in zip(x_vals_bg, mean_vals, n_vals):
            # Print the median/mean precipitation value above the N bar
            ax2.text(x, n + y_offset, f"{m_val:.2f} mm", ha='center', va='bottom', 
                     fontsize=9, color='dimgray', rotation=90)
                     
        # Plot Lines and Uncertainty Shadows
        for k, method in enumerate(methods):
            d_method = d_metric[d_metric["method"] == method]
            
            # Group by size_bin to get the mean and standard deviation across the CV folds
            grp = d_method.groupby("size_bin", observed=False)["value"]
            means = grp.mean()
            stds = grp.std().fillna(0) # Fill NaN with 0 if only one fold had data for an extreme bin
            
            valid_idx = means.notna()
            x_vals = means.index.astype(float)[valid_idx]
            y_means = means.values[valid_idx]
            y_stds = stds.values[valid_idx]
            
            line, = ax.plot(x_vals, y_means, marker='o', color=COLORS[method], label=method, 
                            linewidth=2.5, markersize=5, alpha=0.9)
                            
            # Fill the +/- 1 Std Dev region
            ax.fill_between(x_vals, y_means - y_stds, y_means + y_stds, color=COLORS[method], alpha=0.2)
            
            if i == 0:
                line_handles.append(line)
                line_labels.append(method)
                
        # Formatting
        ax2.set_ylim(0, ax2.get_ylim()[1] * 1.35) # Make room for the vertically rotated text
        
        ax.set_ylabel(f"{metric}", fontsize=12)
        ax2.set_ylabel("Number of Samples (N)", fontsize=11, color='gray')
        ax2.tick_params(axis='y', labelcolor='gray')
        
        ax.grid(axis='y', linestyle='--', alpha=0.5)
        ax.grid(axis='x', linestyle='--', alpha=0.5)
        
        if i >= 2:
            ax.set_xlabel("Vertgroup Size (n_measurements)", fontsize=13)
            
    # Global legend
    all_handles = line_handles + [bar_handle]
    all_labels = line_labels + ["Number of Samples (Background)"]
    fig.legend(all_handles, all_labels, loc='upper center', bbox_to_anchor=(0.5, 1.05), ncol=3, frameon=True, fontsize=13)
    
    plt.tight_layout()
    out_path = os.path.join(OUT_DIR, "vertgroup_size_metrics_with_uncertainty_mean.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Plot successfully saved to: {out_path}")


if __name__ == "__main__":
    group_sizes = load_vertgroup_sizes()
    df_raw = load_and_merge_data(group_sizes)
    df_metrics, bin_stats = bin_and_compute_metrics(df_raw)
    plot_grid(df_metrics, bin_stats)