#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# script was generated by Tim Kluser with the assistance of GitHub Copilot


import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from utils import perfscores


INPUT_DIR_GAUGEDATA = "/store_new/mch/msrad/radar/radar_database_v2/rf_input_data_qc/"
GAUGE_PATH = os.path.join(INPUT_DIR_GAUGEDATA, "gauge.parquet")
OUT_DIR = "./analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

# allows multiple models
MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "RF": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_noPostProcess/cv_pred_RF_noPostProcess_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
    "GRU_bidirectional": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_Bidirectional/cv_1_GRU_Bidirectional_all_folds.parquet",

}
EST_COL = "y_pred"
REF_COL = "y_obs"

# Temperature threshold for phase classification (Degrees C)
TEMP_THRESH = 2.0 

# Precipitation intensity bounds and labels
BOUNDS = [0, 2/6, 10/6, np.inf] #(2mm/h, 10mm/h)
# BOUND_KEYS = ["0.0-2.0", "2.0-10.0", "10.0-inf"]
BOUND_KEYS = ["{:2.1f}-{:2.1f}".format(BOUNDS[i], BOUNDS[i + 1]) for i in range(len(BOUNDS) - 1)]
BOUND_TITLES = ["R $\leq$ 2 mm h$^{-1}$", "2 < R $\leq$ 10 mm h$^{-1}$", "R > 10 mm h$^{-1}$"]

PHASES = ["Solid/mixed phase", "Liquid phase", "All samples"]

PHASES_TITLES    = [
    r"$T \leq 2^\circ\mathrm{C}$ (solid/mixed)", 
    r"$T > 2^\circ\mathrm{C}$ (liquid)", 
    "All samples"
]
PHASES_TITLES    = [
    r"$T \leq 2^\circ\mathrm{C}$", 
    r"$T > 2^\circ\mathrm{C}$", 
    "All"
]
METRICS = ["RMSE", "scatter", "logBias", "ED"]

# Plotting colors
# COLORS = ['#0072B2', '#E69F00', '#555555', '#AAAAAA'] 

def load_and_merge_data():
    print("Loading gauge temperature data ")
    # Updated to the correct column name: TRE200S0
    gauge_df = pd.read_parquet(GAUGE_PATH, columns=["TRE200S0"])
    
    all_data = []
    for method, path in MODELS.items():
        if not os.path.exists(path):
            print(f"Skipping {method}: File not found ({path})")
            continue
            
        print(f"Loading predictions for {method} ")
        df = pd.read_parquet(path)
        
        if "split" in df.columns:
            df["__split__"] = df["split"].astype(str).str.lower()
        elif "is_train" in df.columns:
            df["__split__"] = np.where(df["is_train"].astype(bool), "train", "test")
            
        df["__fold__"] = df["fold"].astype(str)
        df["method"] = method
        
        if "vertgroup" in df.columns:
            df = pd.merge(df, gauge_df, left_on="vertgroup", right_index=True, how="left")
        else:
            raise KeyError(f"Column 'vertgroup' missing in {method} data. Cannot map temperature.")
            
        all_data.append(df)
        
    return pd.concat(all_data, ignore_index=True)


def compute_metrics(df):
    rows = []
    df_test = df[df["__split__"] == "test"].copy()
    
    phase_masks = {
        "Solid/mixed phase": df_test["TRE200S0"] <= TEMP_THRESH,
        "Liquid phase": df_test["TRE200S0"] > TEMP_THRESH,
        "All samples": pd.Series(True, index=df_test.index)
    }
    
    print("Computing metrics across folds, phases, and intensity bounds ")
    for phase_name, mask in phase_masks.items():
        df_phase = df_test[mask]
        
        for method, df_method in df_phase.groupby("method"):
            for fold, d_fold in df_method.groupby("__fold__"):
                
                metrics_by_bound = perfscores(
                    d_fold[EST_COL].to_numpy(),
                    d_fold[REF_COL].to_numpy(),
                    bounds=BOUNDS
                )
                
                for bound_key, mdict in metrics_by_bound.items():
                    if bound_key in BOUND_KEYS:
                        for metric_name in METRICS + ["N"]:
                            m_key = "N" if metric_name == "N" else metric_name
                            val = mdict.get(m_key, np.nan)
                            
                            rows.append({
                                "phase": phase_name,
                                "method": method,
                                "fold": fold,
                                "bound": bound_key,
                                "metric": metric_name,
                                "value": float(val) if np.isfinite(val) else np.nan
                            })
                            
    return pd.DataFrame(rows)

def compute_metrics_noBounds(df):
    rows = []
    df_test = df[df["__split__"] == "test"].copy()
    
    phase_masks = {
        "Solid/mixed phase": df_test["TRE200S0"] <= TEMP_THRESH,
        "Liquid phase": df_test["TRE200S0"] > TEMP_THRESH,
        "All samples": pd.Series(True, index=df_test.index)
    }
    
    print("Computing metrics across folds and phases ")
    for phase_name, mask in phase_masks.items():
        df_phase = df_test[mask]
        
        for method, df_method in df_phase.groupby("method"):
            for fold, d_fold in df_method.groupby("__fold__"):
                
                metrics_by_bound = perfscores(
                    d_fold[EST_COL].to_numpy(),
                    d_fold[REF_COL].to_numpy()
                )
                
                mdict = metrics_by_bound.get("all", {})
                for metric_name in METRICS + ["N"]:
                    m_key = "N" if metric_name == "N" else metric_name
                    val = mdict.get(m_key, np.nan)
                    
                    rows.append({
                        "phase": phase_name,
                        "method": method,
                        "fold": fold,
                        "metric": metric_name,
                        "value": float(val) if np.isfinite(val) else np.nan
                    })
                            
    return pd.DataFrame(rows)

def plot_grid_withBounds(metrics_df):
    print("Generating plot ")
    methods = list(MODELS.keys())
    n_methods = len(methods)
    
    fig, axes = plt.subplots(3, 3, figsize=(16, 10), sharex=True)
    bar_width = 0.8 / n_methods
    x_positions = np.arange(len(METRICS))
    
    for i, phase in enumerate(PHASES):
        for j, bound in enumerate(BOUND_KEYS):
            ax = axes[i, j]
            d = metrics_df[(metrics_df["phase"] == phase) & (metrics_df["bound"] == bound)]
            
            enum_letter = chr(ord('a') + i * 3 + j)
            
            if not d.empty:
                n_series = d[(d["method"] == methods[0]) & (d["metric"] == "N")]["value"]
                total_N = int(n_series.sum())
            else:
                total_N = 0
            
            ax.set_title(f"{enum_letter})", loc='left', fontsize=11, fontweight='bold')

            ax.annotate(f"N={total_N:,}", xy=(0.02, 0.95), xycoords='axes fraction', 
                        fontsize=11, fontweight='bold', va='top', ha='left',
                        bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="none", alpha=0.7))
            
            for k, method in enumerate(methods):
                d_method = d[d["method"] == method]
                
                means, errs = [], []
                for m in METRICS:
                    vals = d_method[d_method["metric"] == m]["value"].dropna()
                    means.append(vals.mean() if not vals.empty else 0)
                    errs.append(vals.std() if not vals.empty else 0)
                    
                offset = (k - n_methods/2 + 0.5) * bar_width
                # color = COLORS[k % len(COLORS)]
                
                bars = ax.bar(x_positions + offset, means, bar_width, yerr=errs, capsize=2, edgecolor='white', linewidth=0.5,
                              label=method if i==0 and j==2 else "")
                
                for bar, err in zip(bars, errs):
                    height = bar.get_height()
                    if height == 0 and err == 0: continue
                    
                    y_pos = height + err + 0.1 * np.sign(height) if height != 0 else height + err + 0.1
                    va = 'bottom' if height >= 0 else 'top'
                    
                    ax.text(bar.get_x() + bar.get_width()/2, y_pos, f'{height:.2f}', 
                            ha='center', va=va, rotation=90, fontsize=8, color='gray')

            if i == 0:
                ax.set_title(BOUND_TITLES[j], fontsize=14, pad=15)
            if j == 0:
                ax.set_ylabel(PHASES_TITLES[i], fontsize=12, labelpad=10)
                
            ax.set_xticks(x_positions)
            ax.set_xticklabels(METRICS)
            
            ax.axhline(0, color='black', linewidth=0.8)
            ax.grid(axis='y', linestyle='--', alpha=0.5)
            
            y_min, y_max = ax.get_ylim()
            ax.set_ylim(y_min * 1.2 if y_min < 0 else 0, y_max * 1.2)

    fig.legend(loc='upper right', 
            #    bbox_to_anchor=(0.98, 0.98),
               ncol=1, frameon=True)
    plt.tight_layout(rect=[0, 0, 0.92, 1])
    
    out_path = os.path.join(OUT_DIR, "phase_intensity_metrics_grid.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Plot successfully saved to: {out_path}")

def plot_grid_noBounds(metrics_df):
    print("Generating bar plot grid ")
    methods = list(MODELS.keys())
    n_methods = len(methods)
    
    fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharey=True)
    
    bar_width = 0.8 / n_methods
    x_positions = np.arange(len(METRICS))
    
    for i, phase in enumerate(PHASES):
        ax = axes[i]
        d = metrics_df[metrics_df["phase"] == phase]
        
        enum_letter = chr(ord('a') + i)
        
        if not d.empty:
            n_series = d[(d["method"] == methods[0]) & (d["metric"] == "N")]["value"]
            total_N = int(n_series.sum())
        else:
            total_N = 0
        
        ax.set_title(f"{enum_letter}) {PHASES_TITLES[i]}", loc='left', fontsize=13, fontweight='bold', pad=10)
        ax.annotate(f"N={total_N:,}", xy=(0.02, 0.95), xycoords='axes fraction', 
                    fontsize=11, fontweight='bold', va='top', ha='left',
                    bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="none", alpha=0.7))
        
        for k, method in enumerate(methods):
            d_method = d[d["method"] == method]
            
            means, errs = [], []
            for m in METRICS:
                vals = d_method[d_method["metric"] == m]["value"].dropna()
                means.append(vals.mean() if not vals.empty else 0)
                errs.append(vals.std() if not vals.empty else 0)
                
            offset = (k - n_methods/2 + 0.5) * bar_width
            # color = COLORS[k % len(COLORS)]
            
            bars = ax.bar(x_positions + offset, means, bar_width, yerr=errs, capsize=2, 
                        edgecolor='white', linewidth=0.5,
                          label=method if i == 2 else "")
            
            for bar, err in zip(bars, errs):
                height = bar.get_height()
                if height == 0 and err == 0: continue
                
                y_pos = height + err + 0.1 * np.sign(height) if height != 0 else height + err + 0.1
                va = 'bottom' if height >= 0 else 'top'
                
                ax.text(bar.get_x() + bar.get_width()/2, y_pos, f'{height:.2f}', 
                        ha='center', va=va, rotation=90, fontsize=8, color='gray')

        ax.set_xticks(x_positions)
        ax.set_xticklabels(METRICS)
        
        ax.axhline(0, color='black', linewidth=0.8)
        ax.grid(axis='y', linestyle='--', alpha=0.5)
        
        y_min, y_max = ax.get_ylim()
        ax.set_ylim(y_min * 1.2 if y_min < 0 else 0, y_max * 1.2)

    # Global legend mapped to the right of the figure bounds
    fig.legend(loc='upper right', bbox_to_anchor=(0.99, 0.92), ncol=1, frameon=True)
    plt.tight_layout(rect=[0, 0, 0.88, 1])
    
    out_path = os.path.join(OUT_DIR, "phase_bar_grid_1x3.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Plot successfully saved to: {out_path}")


def plot_grid_metrics_as_subplots(metrics_df):
    print("Generating bar plot grid (Metrics as subplots, Phases on X-axis) ")
    methods = list(MODELS.keys())
    n_methods = len(methods)
    
    fig, axes = plt.subplots(1, len(METRICS), figsize=(5 * len(METRICS), 6))
    
    bar_width = 0.8 / n_methods
    x_positions = np.arange(len(PHASES)) # X-axis now represents phases
    
    for i, metric in enumerate(METRICS):
        ax = axes[i]
        
        d_metric = metrics_df[metrics_df["metric"] == metric]
        
        enum_letter = chr(ord('a') + i)
        ax.set_title(f"{enum_letter}) {metric}", loc='left', fontsize=14, fontweight='bold', pad=15)
        
        phase_Ns = []
        for phase in PHASES:
            d_phase_N = metrics_df[(metrics_df["phase"] == phase) & (metrics_df["metric"] == "N")]
            if not d_phase_N.empty:
                n_val = int(d_phase_N[d_phase_N["method"] == methods[0]]["value"].sum())
            else:
                n_val = 0
            phase_Ns.append(n_val)
            
        for k, method in enumerate(methods):
            means, errs = [], []
            
            for phase in PHASES:
                vals = d_metric[(d_metric["method"] == method) & (d_metric["phase"] == phase)]["value"].dropna()
                means.append(vals.mean() if not vals.empty else 0)
                errs.append(vals.std() if not vals.empty else 0)
                
            offset = (k - n_methods/2 + 0.5) * bar_width
            
            bars = ax.bar(x_positions + offset, means, bar_width, yerr=errs, capsize=2, 
                          edgecolor='white', linewidth=0.5,
                          label=method if i == len(METRICS) - 1 else "")
            
            for bar, err in zip(bars, errs):
                height = bar.get_height()
                if height == 0 and err == 0: continue
                
                y_pos = 1.05 * np.sign(height) * (np.abs(err) + np.abs(height)) if height != 0 else height + err + 0.1
                va = 'bottom' if height >= 0 else 'top'
                
                ax.text(bar.get_x() + bar.get_width()/2, y_pos, f'{height:.2f}', 
                        ha='center', va=va, rotation=90, fontsize=8, color='gray')

        ax.set_xticks(x_positions)
        xtick_labels = [f"{pt}\n(N={n:,})" for pt, n in zip(PHASES_TITLES, phase_Ns)]
        ax.set_xticklabels(xtick_labels, fontsize=11, rotation = 30 )
        
        ax.axhline(0, color='black', linewidth=0.8)
        ax.grid(axis='y', linestyle='--', alpha=0.5)
        
        y_min, y_max = ax.get_ylim()
        y_min_adj = y_min * 1.2 if y_min < 0 else (y_min * 0.8 if y_min > 0 else 0)
        ax.set_ylim(y_min_adj, y_max * 1.2)

    fig.legend(loc='upper right', bbox_to_anchor=(0.99, 0.92), ncol=1, frameon=True)
    plt.tight_layout(rect=[0, 0, 0.88, 1])
    
    out_path = os.path.join(OUT_DIR, "metrics_bar_grid_by_phase.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Plot successfully saved to: {out_path}")

def plot_large_grid_intensity_vs_metric(metrics_df):
    print("Generating large grid (Y: Intensity Bounds, X: Metrics, Subplot-X: Phases) ")
    methods = list(MODELS.keys())
    n_methods = len(methods)
    
    n_rows = len(BOUND_KEYS)
    n_cols = len(METRICS)


    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 15))
    
    bar_width = 0.8 / n_methods
    x_positions = np.arange(len(PHASES)) # X-axis represents phases
    
    for i, bound in enumerate(BOUND_KEYS):
        
        phase_Ns = []
        for phase in PHASES:
            d_N = metrics_df[(metrics_df["bound"] == bound) & (metrics_df["phase"] == phase) & (metrics_df["metric"] == "N")]
            if not d_N.empty:
                n_val = int(d_N[d_N["method"] == methods[0]]["value"].sum())
            else:
                n_val = 0
            phase_Ns.append(n_val)
            
        for j, metric in enumerate(METRICS):
            ax = axes[i, j]
            
            d_sub = metrics_df[(metrics_df["metric"] == metric) & (metrics_df["bound"] == bound)]
            
            enum_letter = chr(ord('a') + i * n_cols + j)
            ax.set_title(f"{enum_letter})", loc='left', fontsize=13, fontweight='bold')
            
            if i == 0:
                ax.set_title(metric, loc='center', fontsize=16, fontweight='bold', pad=15)
                
            if j == 0:
                ax.set_ylabel(BOUND_TITLES[i], fontsize=14, fontweight='bold', labelpad=10)
            
            for k, method in enumerate(methods):
                means, errs = [], []
                
                for phase in PHASES:
                    vals = d_sub[(d_sub["method"] == method) & (d_sub["phase"] == phase)]["value"].dropna()
                    means.append(vals.mean() if not vals.empty else 0)
                    errs.append(vals.std() if not vals.empty else 0)
                    
                offset = (k - n_methods/2 + 0.5) * bar_width
                
                bars = ax.bar(x_positions + offset, means, bar_width, yerr=errs, capsize=2, 
                              edgecolor='white', linewidth=0.5,
                              label=method if (i == 0 and j == n_cols - 1) else "")
                
                for bar, err in zip(bars, errs):
                    height = bar.get_height()
                    if height == 0 and err == 0: continue
                    
                    y_pos = 1.05 * np.sign(height) * (np.abs(err) + np.abs(height)) if height != 0 else height + err + 0.1
                    va = 'bottom' if height >= 0 else 'top'
                    
                    ax.text(bar.get_x() + bar.get_width()/2, y_pos, f'{height:.2f}', 
                            ha='center', va=va, rotation=90, fontsize=8, color='gray')

            ax.set_xticks(x_positions)
            xtick_labels = [f"{pt}\n(N={n:,})" for pt, n in zip(PHASES_TITLES, phase_Ns)]
            
            ax.set_xticklabels(xtick_labels, fontsize=11, rotation=25, ha='right')
            
            ax.axhline(0, color='black', linewidth=0.8)
            ax.grid(axis='y', linestyle='--', alpha=0.5)
            
    #
    for ax in axes.flatten():
        y_min, y_max = ax.get_ylim()
        y_min_adj = y_min * 1.3 if y_min < 0 else (y_min * 0.8 if y_min > 0 else 0)
        ax.set_ylim(y_min_adj, y_max * 1.3)

    # Global legend mapped to the right of the figure bounds
    fig.legend(loc='upper right', bbox_to_anchor=(0.98, 1), ncol=1, frameon=True, fontsize=11)
    
    # Adjust layout to fit everything without overlap
    plt.tight_layout(rect=[0, 0, 0.92, 1], h_pad=2.0)
    
    out_path = os.path.join(OUT_DIR, "metrics_large_grid_intensity_vs_metric.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Plot successfully saved to: {out_path}")

if __name__ == "__main__":
    df_raw = load_and_merge_data()

    # with precipitation bounds
    # df_metrics = compute_metrics(df_raw)
    # plot_grid_withBounds(df_metrics)

    # # without precipitation bounds
    # df_metrics = compute_metrics_noBounds(df_raw)
    # plot_grid_noBounds(df_metrics)

    # df_metrics = compute_metrics_noBounds(df_raw)
    # plot_grid_metrics_as_subplots(df_metrics)

    df_metrics = compute_metrics(df_raw)
    plot_large_grid_intensity_vs_metric(df_metrics)