#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script was generated by Tim Kluser with the assistance of GitHub Copilot

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

OUT_DIR = "./analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

# Define the two models to compare
MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
}

EST_COL = "y_pred"
REF_COL = "y_obs"

# Thresholds
PRED_THRESH = 0.05  # Consider predictions <= x as "0" (Model says no rain)
OBS_THRESH = 0.05   # Consider observations > x  (Gauge says rain)

# Colors for consistency
COLORS = {'RF_spline': '#1f77b4', 'GRU_optimized': '#ff7f0e'}

def generate_misses_plot():
    print("Generating distribution plots for Misses...")
    
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    
    model_misses = {}
    model_labels = {}
    model_means = {}
    max_val = 0
    
    for method, path in MODELS.items():
        if not os.path.exists(path):
            print(f"Skipping {method}: File not found ({path})")
            continue
            
        print(f"Loading predictions for {method}...")
        
        df = pd.read_parquet(path, columns=[EST_COL, REF_COL, "split"])
        
        # Strictly filter for the TEST split
        df = df[df["split"].astype(str).str.lower() == "test"]
            
        # Filter for False Negatives (Misses): Model predicts basically 0, but gauge > 0
        df_misses = df[(df[EST_COL] <= PRED_THRESH) & (df[REF_COL] > OBS_THRESH)].copy()
        
        # Extract the ACTUAL GAUGE values that were missed
        missed_obs = df_misses[REF_COL].dropna().to_numpy()
        
        # Calculate mean of the missed events
        mean_val = np.mean(missed_obs) if len(missed_obs) > 0 else 0
        model_means[method] = mean_val
        
        # Store the label with the exact count of missed samples AND the mean missed amount
        model_labels[method] = f"{method} (N={len(missed_obs):,}, Mean={mean_val:.3f} mm)"
        
        # Filter out extreme outliers for visualization purposes
        if len(missed_obs) > 0:
            # cap = np.percentile(missed_obs, 99.9)
            # missed_obs_capped = missed_obs[missed_obs <= cap]
            model_misses[method] = missed_obs
            max_val = max(max_val, np.max(missed_obs))
            
        print(f" - {method}: Found {len(missed_obs):,} TEST samples missed (Mean actual rain: {mean_val:.3f} mm)")

    # Define common binning so both models are plotted fairly
    if max_val == 0: max_val = 1 # Fallback if no misses
    bins_log = np.linspace(0, max_val, int(np.ceil(max_val/0.1) - 1))
    bins_linear = np.linspace(0, 0.7, 7)

    ax1 = axes[0]
    for method, obs in model_misses.items():
        if len(obs) == 0: continue
        # Plot the distribution
        sns.histplot(obs, bins=bins_linear, stat="density", 
                     color=COLORS[method], label=model_labels[method], alpha=0.4, ax=ax1, 
                     line_kws={'linewidth': 2})
        # Mark the mean with a dashed vertical line
        ax1.axvline(model_means[method], color=COLORS[method], linestyle='--', linewidth=2, alpha=0.8)

    ax1.set_title("Density of Missed Rainfall", fontsize=14)
    ax1.set_xlabel("Actual Gauge Precipitation [mm/10min]", fontsize=12)
    ax1.set_ylabel("Density", fontsize=12)
    ax1.grid(True, linestyle='--', alpha=0.5)
    ax1.legend(fontsize=11)

    ax2 = axes[1]
    for method, obs in model_misses.items():
        if len(obs) == 0: continue
        # Plot the histograms
        ax2.hist(obs, bins=bins_log, density=True, color=COLORS[method], 
                 label=model_labels[method], alpha=0.4, log=True)
        ax2.hist(obs, bins=bins_log, density=True, color=COLORS[method], 
                 histtype='step', log=True, linewidth=1.5)
        # Mark the mean with a dashed vertical line
        ax2.axvline(model_means[method], color=COLORS[method], linestyle='--', linewidth=2, alpha=0.8)

    ax2.set_title("Density of Missed Rainfall (Log Scale)", fontsize=14)
    ax2.set_xlabel("Actual Gauge Precipitation [mm/10min]", fontsize=12)
    ax2.set_ylabel("Density (Log Scale)", fontsize=12)
    ax2.grid(True, linestyle='--', alpha=0.5, which='both')
    ax2.legend(fontsize=11)

    # Global title
    plt.suptitle("TEST Set Distribution of False Negatives (Model $\leq$ 0.05 mm/10min, but Gauge > 0.05 mm/10min)\n(X-Axis shows the actual rainfall amount that was missed)", 
                 fontsize=16, fontweight='bold', y=1.08)
    

    plt.tight_layout()
    
    out_path = os.path.join(OUT_DIR, "distribution_misses.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"\nSuccess! Plot saved to: {out_path}")

if __name__ == "__main__":
    generate_misses_plot()
