#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script that generates a histogram for predictions with reference close to 0
# script was generated by Tim Kluser with the assistance of GitHub Copilot

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

OUT_DIR = "./analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

# Define the two models to compare
MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
}

EST_COL = "y_pred"
REF_COL = "y_obs"

# Colors for consistency
COLORS = {'RF_spline': '#1f77b4', 'GRU_optimized': '#ff7f0e'}

def generate_distribution_plot():
    print("Generating distribution plots for Ref == 0 (TEST split only)...")
    
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    
    model_preds = {}
    model_labels = {}
    model_means = {}
    max_val = 0
    
    for method, path in MODELS.items():
        if not os.path.exists(path):
            print(f"Skipping {method}: File not found ({path})")
            continue
            
        print(f"Loading predictions for {method}...")
        
        df = pd.read_parquet(path, columns=[EST_COL, REF_COL, "split"])
        
        # Strictly filter for the TEST split
        df = df[df["split"].astype(str).str.lower() == "test"]
        
            
        # Filter for samples where reference precipitation is exactly 0
        df_zero = df[df[REF_COL] <= 0.05].copy()
        
        # Extract the predictions, drop NaNs, and convert to numpy array
        preds = df_zero[EST_COL].dropna().to_numpy()
        
        # Clip all negative predictions to 0
        preds = np.maximum(preds, 0)
        
        # Calculate mean
        mean_val = np.mean(preds)
        model_means[method] = mean_val
        
        # Store the label with the exact count of samples AND the mean
        model_labels[method] = f"{method} (N={len(preds):,}, Mean={mean_val:.3f} mm)"
        
        # Filter out extreme outliers for visualization purposes
        if len(preds) > 0:
            cap = np.percentile(preds, 99.9)
            preds_capped = preds[preds <= cap]
            model_preds[method] = preds_capped
            max_val = max(max_val, np.max(preds_capped))
            
        print(f" - {method}: Found {len(preds):,} TEST samples where gauge was $\leq$ 0.05 mm/10min (Mean: {mean_val:.3f} mm)")

    bins = np.linspace(0, max_val, 100)

    ax1 = axes[0]
    for method, preds in model_preds.items():
        # Plot the distribution
        sns.histplot(preds, bins=bins, kde=True, 
                     color=COLORS[method], label=model_labels[method], alpha=0.4, ax=ax1, 
                     line_kws={'linewidth': 2})
        # Mark the mean with a dashed vertical line
        ax1.axvline(model_means[method], color=COLORS[method], linestyle='--', linewidth=2, alpha=0.8)

    ax1.set_title("Histogram of Dry Period Predictions", fontsize=14)
    ax1.set_xlabel("Predicted Precipitation [mm/10min]", fontsize=12)
    ax1.set_ylabel("Count", fontsize=12)
    ax1.grid(True, linestyle='--', alpha=0.5)
    ax1.legend(fontsize=11)

    ax2 = axes[1]
    for method, preds in model_preds.items():
        # Plot the histograms
        ax2.hist(preds, bins=bins, color=COLORS[method], 
                 label=model_labels[method], alpha=0.4, log=True)
        ax2.hist(preds, bins=bins, color=COLORS[method], 
                 histtype='step', log=True, linewidth=1.5)
        # Mark the mean with a dashed vertical line
        ax2.axvline(model_means[method], color=COLORS[method], linestyle='--', linewidth=2, alpha=0.8)

    ax2.set_title("Histogram of Dry Period Predictions (Log scale)", fontsize=14)
    ax2.set_xlabel("Predicted Precipitation [mm/10min]", fontsize=12)
    ax2.set_ylabel("Count (Log Scale)", fontsize=12)
    ax2.grid(True, linestyle='--', alpha=0.5, which='both')
    ax2.legend(fontsize=11)

    # Global title
    plt.suptitle("TEST Set Distribution of Model Predictions when Reference Precipitation $\leq$ 0.05mm/10min\n(Negative estimates clipped to 0, dashed lines = Mean)", 
                 fontsize=16, fontweight='bold', y=1.08)
    
    plt.tight_layout()
    
    out_path = os.path.join(OUT_DIR, "distribution_ref_zero.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"\nSuccess! Plot saved to: {out_path}")

if __name__ == "__main__":
    generate_distribution_plot()