#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# script that generates scatter plots for the predictions vs true values for multiple models
# script was generated by Tim Kluser with the assistance of GitHub Copilot


import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# allows four models
MODELS = {
    "RF_spline": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_spline/cv_pred_RF_spline_all_folds.parquet",
    "RF": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/RF_noPostProcess/cv_pred_RF_noPostProcess_all_folds.parquet",
    "GRU_optimized": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_optimized3/cv_1_GRU_optimized3_all_folds.parquet",
    "GRU_bidirectional": "/scratch/mch/tkluser/rainforest_semester_project/saved_models/GRU_Bidirectional/cv_1_GRU_Bidirectional_all_folds.parquet",
}

OUT_DIR = "analyse_models/plots"
os.makedirs(OUT_DIR, exist_ok=True)

EST_COL = "y_pred"
REF_COL = "y_obs"

def load_split_data(method, path):
    """Loads the parquet file, detects the split column, and returns a clean DataFrame."""
    if not os.path.exists(path):
        print(f"Warning: Missing file for {method} at {path}")
        return pd.DataFrame()
        
    print(f"Loading data for {method}...")
    df = pd.read_parquet(path)
    
    if "split" in df.columns:
        df["__split__"] = df["split"].astype(str).str.lower()
    elif "is_train" in df.columns:
        df["__split__"] = np.where(df["is_train"].astype(bool), "train", "test")
    elif "dataset" in df.columns:
        df["__split__"] = df["dataset"].astype(str).str.lower()
    else:
        print(f"Warning: Could not find split indicator for {method}.")
        return pd.DataFrame()
        
    return df[[EST_COL, REF_COL, "__split__"]].dropna()


def generate_scatter_grid():
    fig, axes = plt.subplots(nrows=2, ncols=4, figsize=(20, 10), sharex=True, sharey=True)
    
    splits = ["train", "test"]
    methods = list(MODELS.keys())
    
    hb = None 
    
    # Loop over columns (models) and rows (splits)
    for j, method in enumerate(methods):
        path = MODELS[method]
        df = load_split_data(method, path)
        
        for i, split in enumerate(splits):
            ax = axes[i, j]
            
            if df.empty or df[df["__split__"] == split].empty:
                ax.text(0.5, 0.5, "Data Unavailable", ha='center', va='center', fontsize=12, color='gray')
                ax.set_title(f"{method}: {split.upper()} scatter")
                ax.grid(True, alpha=0.2)
                continue
            
            d = df[df["__split__"] == split]
            est = d[EST_COL].to_numpy()
            ref = d[REF_COL].to_numpy()
            
            valid_mask = (est >= 0) & (ref >= 0) & np.isfinite(est) & np.isfinite(ref)
            est = est[valid_mask]
            ref = ref[valid_mask]
            
            hb = ax.hexbin(ref, est, bins="log", mincnt=1, cmap="viridis")
            
            max_val = max(np.max(ref), np.max(est)) if len(ref) > 0 else 50
            ax.plot([0, max_val], [0, max_val], color='steelblue', linewidth=1.5, label="1:1 line")
            
            # Formatting
            ax.set_title(f"{method}: {split.upper()} scatter", fontsize=13)
            ax.grid(True, which="both", alpha=0.3)
            
            # Add Y-axis labels to the leftmost column only (j == 0)
            if j == 0:
                ax.set_ylabel("Estimated precip [mm]", fontsize=12)
            # Add X-axis labels to the bottom row only (i == 1)
            if i == 1:
                ax.set_xlabel("Reference precip [mm]", fontsize=12)
                
            # Add legend to the top-left plot only
            if i == 0 and j == 0:
                ax.legend(loc="upper left")

    plt.tight_layout(rect=[0, 0, 0.92, 1])

    if hb is not None:
        cbar_ax = fig.add_axes([0.93, 0.15, 0.015, 0.7]) 
        cbar = fig.colorbar(hb, cax=cbar_ax, orientation='vertical')
        cbar.set_label('Count / Density (log scale)', fontsize=14, labelpad=15)
        cbar.ax.tick_params(labelsize=11)

    out_path = os.path.join(OUT_DIR, "scatter_grid_models_2x4.png")
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"\nSuccess! Plot saved to: {out_path}")

if __name__ == "__main__":
    generate_scatter_grid()